export const MOCK_PLANS = [
  {
    id: 'seeker',
    name: 'Seeker',
    blurb: 'A simple start.',
    price: 'Free',
    priceAmount: 0,
    currency: 'USD',
    cadence: null,
    featured: false,
    features: ['One daily card', 'Three dreams kept', 'Sun-sign horoscope'],
  },
  {
    id: 'oracle',
    name: 'Oracle',
    blurb: 'The full experience.',
    price: '$9',
    priceAmount: 9,
    currency: 'USD',
    cadence: '/ month',
    featured: true,
    badgeLabel: 'Most chosen',
    features: [
      'All five practices',
      'Unlimited ledger & search',
      'Full natal chart & transits',
      'Voice readings',
      'Cloud sync across devices',
    ],
  },
  {
    id: 'oracle-plus',
    name: 'Oracle+',
    blurb: 'For deeper insight.',
    price: '$19',
    priceAmount: 19,
    currency: 'USD',
    cadence: '/ month',
    featured: false,
    features: [
      'Everything in Oracle',
      'Advanced astrology tools',
      'Early access to new features',
      'Priority support',
    ],
  },
];

export const MOCK_SUBSCRIPTIONS = [
  {
    id: 'sub_liora_free',
    userId: 'user_liora',
    planId: 'seeker',
    status: 'free',
    statusLabel: 'Free membership',
    startedAt: '2024-03-14',
    renewsAt: null,
    paymentSummary: 'No payment method',
  },
  {
    id: 'sub_fiora_oracle',
    userId: 'user_fiora',
    planId: 'oracle',
    status: 'active',
    statusLabel: 'Active membership',
    startedAt: '2024-03-14',
    renewsAt: '2026-06-14',
    paymentSummary: 'Card · 4242',
  },
];
