export const MOCK_READINGS = [
  {
    id: 'reading_fiora_001',
    userId: 'user_fiora',
    practice: 'tarot',
    title: 'The Threefold Mirror',
    summary: 'A three-card spread tracing the present choice and its quiet consequence.',
    tags: ['3 cards'],
    createdAt: '2026-05-25T20:14:00.000Z',
    status: 'complete',
  },
  {
    id: 'reading_fiora_002',
    userId: 'user_fiora',
    practice: 'daily',
    title: 'Bronze hour, water element',
    summary: 'A daily omen for patience, soft focus, and listening before acting.',
    tags: ['Omen'],
    createdAt: '2026-05-25T07:02:00.000Z',
    status: 'complete',
  },
  {
    id: 'reading_fiora_003',
    userId: 'user_fiora',
    practice: 'dream',
    title: 'The bronze key, the corridor',
    summary: 'A recurring threshold dream about locked rooms and inherited choices.',
    tags: ['Lucid'],
    createdAt: '2026-05-24T03:14:00.000Z',
    status: 'complete',
  },
  {
    id: 'reading_fiora_004',
    userId: 'user_fiora',
    practice: 'astrology',
    title: 'Saturn return, opening phase',
    summary: 'A transit note about structure, pressure, and committing to the durable path.',
    tags: ['Transit'],
    createdAt: '2026-05-24T18:40:00.000Z',
    status: 'complete',
  },
  {
    id: 'reading_fiora_005',
    userId: 'user_fiora',
    practice: 'palmistry',
    title: 'Right palm scan',
    summary: 'A palm reading focused on head line clarity and long-term creative discipline.',
    tags: ['Reading'],
    createdAt: '2026-05-23T12:30:00.000Z',
    status: 'complete',
  },
  {
    id: 'reading_fiora_006',
    userId: 'user_fiora',
    practice: 'tarot',
    title: 'The Hermit, reversed',
    summary: 'A single-card prompt about isolation, counsel, and when to rejoin the circle.',
    tags: ['1 card'],
    createdAt: '2026-05-22T21:05:00.000Z',
    status: 'complete',
  },
  {
    id: 'reading_fiora_007',
    userId: 'user_fiora',
    practice: 'dream',
    title: 'A river of paperbacks',
    summary: 'A dream note about memory, archives, and searching for a sentence already known.',
    tags: ['Recurring'],
    createdAt: '2026-05-21T04:22:00.000Z',
    status: 'complete',
  },
  {
    id: 'reading_liora_001',
    userId: 'user_liora',
    practice: 'daily',
    title: 'First light, clear cup',
    summary: 'A simple daily omen about beginning again without overexplaining the past.',
    tags: ['Omen'],
    createdAt: '2026-05-25T08:10:00.000Z',
    status: 'complete',
  },
  {
    id: 'reading_liora_002',
    userId: 'user_liora',
    practice: 'tarot',
    title: 'Page of Cups',
    summary: 'A one-card reading about curiosity, apology, and an unexpected invitation.',
    tags: ['1 card'],
    createdAt: '2026-05-23T19:45:00.000Z',
    status: 'complete',
  },
  {
    id: 'reading_liora_003',
    userId: 'user_liora',
    practice: 'dream',
    title: 'Window over rain',
    summary: 'A short dream record about waiting, weather, and a message left unread.',
    tags: ['Dream'],
    createdAt: '2026-05-20T05:05:00.000Z',
    status: 'complete',
  },
];
