export const MOCK_USERS = [
  {
    id: 'user_liora',
    firstName: 'Liora',
    fullName: 'Liora Vance',
    avatarInitial: 'L',
    email: 'liora@example.com',
    password: 'seeker123',
    birthDate: '1996-03-11',
    birthTime: '04:20',
    birthPlace: 'Lisbon, Portugal',
    roleLabel: 'Seeker',
    sunSign: 'Pisces',
    risingSign: 'Capricorn',
    joinedAt: '2024-03-14',
    subscriptionId: 'sub_liora_free',
  },
  {
    id: 'user_fiora',
    firstName: 'Fiora',
    fullName: 'Fiora Vance',
    avatarInitial: 'F',
    email: 'fiora@example.com',
    password: 'oracle123',
    birthDate: '1992-10-22',
    birthTime: '21:15',
    birthPlace: 'Portland, Oregon',
    roleLabel: 'Oracle',
    sunSign: 'Libra',
    risingSign: 'Cancer',
    joinedAt: '2023-11-02',
    subscriptionId: 'sub_fiora_oracle',
  },
];
